### ISSUE TITLE
Where is the neural network 

### ISSUE THREAD

**Issue by Oussamab21** [AaronX121/Soft-Decision-Tree#1]
Thank you for sharing the code, I can't see where did you use the neural network to produce the soft labels as stated in the paper ?

Regards

**Comment by xuyxu** [comment]
Hi, the target of this Repo is not to conduct knowledge distillation (KD), as I mainly focus on other uses of soft decision tree (SDT).  However, I think the idea lying behind KD is quite intuitive, and can be implemented easily based on this SDT model.

Any question on KD is welcomed ! Actually, I managed to distill knowledges from CNN ensembles into one SDT, and the result is positive.
